import { Roboto } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/Header';
import { AppProvider } from '@/components/AppContext';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Pezzo Perfetto',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <main className='max-w-4xl p-4 mx-auto'>
          <AppProvider>
            <Header />
            {children}
            <footer className='border-t text-center text-gray-500 p-8'>
              &copy; 2023 All rights reserved
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
